{
  "openapi": "3.0.3",
  "info": {
    "title": "API - TuLetra",
    "description": "Esta es la documentación acerca de la api de **Tu letra** para la materia web 2 de la Tudai. La misma fue realizada con Swagger Editor bajo la especificación de OpenAPI V3.",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "comentarios",
      "description": "Comentarios anonimos de las canciones de **tuletra**"
    }
  ],
  "paths": {
    "/comentarios": {
      "get": {
        "tags": [
          "comentarios"
        ],
        "summary": "Recupera todos los comentarios",
        "description": "Recupera un listado de todos los comentarios.",
        "operationId": "getAll",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Número de página para la paginación. **Obligatorio usar `limit`**.\n",
            "required": false,
            "schema": {
              "type": "integer",
              "example": 1
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Cantidad de comentarios por página. **Obligatorio usar `page`**.\n",
            "required": false,
            "schema": {
              "type": "integer",
              "example": 3
            }
          },
          {
            "name": "order",
            "in": "query",
            "description": "Orden de los resultados. Puede ser **\"asc\"** o **\"desc\"**. Si se especifica sin `column`, se usará la columna predeterminada.\n",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "asc",
                "desc"
              ]
            }
          },
          {
            "name": "column",
            "in": "query",
            "description": "Columna para ordenar los resultados. Puede ser **\"id_comentario\", \"autor\", \"positivo\", \"comentario\" o \"id_cancion_fk\".**\nSi se especifica, **debe usarse con `order`**.\n",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "id_comentario",
                "autor",
                "positivo",
                "comentario",
                "id_cancion_fk"
              ]
            }
          },
          {
            "name": "positivo",
            "in": "query",
            "description": "Filtro por campo positivo. Puede ser `true` o `false`.\n",
            "required": false,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id_comentario": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                      },
                      "autor": {
                        "type": "string",
                        "example": "Carlos"
                      },
                      "positivo": {
                        "type": "boolean",
                        "example": 1
                      },
                      "comentario": {
                        "type": "string",
                        "example": "Me encanta la cancion"
                      },
                      "id_cancion_fk": {
                        "type": "integer",
                        "format": "int64",
                        "example": 12
                      }
                    }
                  },
                  "example": [
                    {
                      "id_comentario": 1,
                      "autor": "Carlos",
                      "positivo": true,
                      "comentario": "Me encanta la canción",
                      "id_cancion_fk": 12
                    },
                    {
                      "id_comentario": 2,
                      "autor": "Ana",
                      "positivo": false,
                      "comentario": "No es de mi gusto",
                      "id_cancion_fk": 10
                    },
                    {
                      "id_comentario": 3,
                      "autor": "Luis",
                      "positivo": true,
                      "comentario": "Excelente interpretación",
                      "id_cancion_fk": 15
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Parámetros inválidos",
            "content": {
              "application/json": {
                "examples": {
                  "invalidParameters": {
                    "summary": "Parámetros inválidos",
                    "value": {
                      "mensaje": "Los parámetros no corresponden."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "No existen comentarios para esa página",
            "content": {
              "application/json": {
                "examples": {
                  "notFound": {
                    "summary": "No encontrado",
                    "value": {
                      "mensaje": "No se encontraron resultados para el recurso solicitado."
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "comentarios"
        ],
        "summary": "Crear un comentario",
        "description": "Crear un nuevo comentario para una cancion.",
        "operationId": "createComment",
        "requestBody": {
          "description": "Objeto para crear comentario",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "autor": {
                    "type": "string",
                    "example": "Carlos"
                  },
                  "positivo": {
                    "type": "boolean",
                    "example": 1
                  },
                  "comentario": {
                    "type": "string",
                    "example": "Me encanta la cancion"
                  },
                  "id_cancion_fk": {
                    "type": "integer",
                    "format": "int64",
                    "example": 12
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Operación exitosa",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id_comentario": {
                      "type": "integer",
                      "format": "int64",
                      "example": 1
                    },
                    "autor": {
                      "type": "string",
                      "example": "Carlos"
                    },
                    "positivo": {
                      "type": "boolean",
                      "example": 1
                    },
                    "comentario": {
                      "type": "string",
                      "example": "Me encanta la cancion"
                    },
                    "id_cancion_fk": {
                      "type": "integer",
                      "format": "int64",
                      "example": 12
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/comentarios/{idComentario}": {
      "get": {
        "tags": [
          "comentarios"
        ],
        "summary": "Comentario por su id",
        "description": "Trae un comentario por su id",
        "operationId": "getComentarioById",
        "parameters": [
          {
            "name": "idComentario",
            "in": "path",
            "description": "El id del comentario a recuperar. debe ser un valor numerico entero.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id_comentario": {
                      "type": "integer",
                      "format": "int64",
                      "example": 1
                    },
                    "autor": {
                      "type": "string",
                      "example": "Carlos"
                    },
                    "positivo": {
                      "type": "boolean",
                      "example": 1
                    },
                    "comentario": {
                      "type": "string",
                      "example": "Me encanta la cancion"
                    },
                    "id_cancion_fk": {
                      "type": "integer",
                      "format": "int64",
                      "example": 12
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Parámetros inválidos",
            "content": {
              "application/json": {
                "examples": {
                  "invalidParameters": {
                    "summary": "Solicitud Mala",
                    "value": {
                      "mensaje": "La solicitud fue mal generada."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Comentario no encontrado",
            "content": {
              "application/json": {
                "examples": {
                  "invalidParameters": {
                    "summary": "No encontrado",
                    "value": {
                      "mensaje": "No se encontraron resultados para el recurso solicitado."
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "comentarios"
        ],
        "summary": "Modificar comentario",
        "description": "Modificar comentario de una cancion.",
        "operationId": "modificarComentario",
        "parameters": [
          {
            "name": "idComentario",
            "in": "path",
            "description": "id de comentario",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "description": "Objeto para crear comentario",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "autor": {
                    "type": "string",
                    "example": "Carlos"
                  },
                  "positivo": {
                    "type": "boolean",
                    "example": 1
                  },
                  "comentario": {
                    "type": "string",
                    "example": "Me encanta la cancion"
                  },
                  "id_cancion_fk": {
                    "type": "integer",
                    "format": "int64",
                    "example": 12
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id_comentario": {
                      "type": "integer",
                      "format": "int64",
                      "example": 1
                    },
                    "autor": {
                      "type": "string",
                      "example": "Carlos"
                    },
                    "positivo": {
                      "type": "boolean",
                      "example": 1
                    },
                    "comentario": {
                      "type": "string",
                      "example": "Me encanta la cancion"
                    },
                    "id_cancion_fk": {
                      "type": "integer",
                      "format": "int64",
                      "example": 12
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Faltan completar campos",
            "content": {
              "application/json": {
                "examples": {
                  "invalidParameters": {
                    "summary": "Solicitud Mala",
                    "value": {
                      "mensaje": "La solicitud fue mal generada."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "No existe comentario con ese id",
            "content": {
              "application/json": {
                "examples": {
                  "invalidParameters": {
                    "summary": "No encontrado",
                    "value": {
                      "mensaje": "No se encontraron resultados para el recurso solicitado."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/canciones/{idCancion}/comentarios": {
      "get": {
        "tags": [
          "comentarios"
        ],
        "summary": "Comentarios por id de cancion",
        "description": "Trae un listado de comentarios de una cancion",
        "operationId": "getComentarioByCancion",
        "parameters": [
          {
            "name": "idCancion",
            "in": "path",
            "description": "El id de la cancion que se quiere recuperar los comentarios.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Operación exitosa",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id_comentario": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                      },
                      "autor": {
                        "type": "string",
                        "example": "Carlos"
                      },
                      "positivo": {
                        "type": "boolean",
                        "example": 1
                      },
                      "comentario": {
                        "type": "string",
                        "example": "Me encanta la cancion"
                      },
                      "id_cancion_fk": {
                        "type": "integer",
                        "format": "int64",
                        "example": 12
                      }
                    }
                  },
                  "example": [
                    {
                      "id_comentario": 1,
                      "autor": "Carlos",
                      "positivo": true,
                      "comentario": "Me encanta la canción",
                      "id_cancion_fk": 12
                    },
                    {
                      "id_comentario": 2,
                      "autor": "Ana",
                      "positivo": false,
                      "comentario": "No es de mi gusto",
                      "id_cancion_fk": 10
                    },
                    {
                      "id_comentario": 3,
                      "autor": "Luis",
                      "positivo": true,
                      "comentario": "Excelente interpretación",
                      "id_cancion_fk": 15
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Solicitud Mala",
            "content": {
              "application/json": {
                "examples": {
                  "invalidParameters": {
                    "summary": "Solicitud Mala",
                    "value": {
                      "mensaje": "La solicitud fue mal generada."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "No existe cancion para ese id",
            "content": {
              "application/json": {
                "examples": {
                  "invalidParameters": {
                    "summary": "No encontrado",
                    "value": {
                      "mensaje": "No se encontraron resultados para el recurso solicitado."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Comentario": {
        "type": "object",
        "properties": {
          "id_comentario": {
            "type": "integer",
            "format": "int64",
            "example": 1
          },
          "autor": {
            "type": "string",
            "example": "Carlos"
          },
          "positivo": {
            "type": "boolean",
            "example": 1
          },
          "comentario": {
            "type": "string",
            "example": "Me encanta la cancion"
          },
          "id_cancion_fk": {
            "type": "integer",
            "format": "int64",
            "example": 12
          }
        }
      },
      "ComentarioReqBody": {
        "type": "object",
        "properties": {
          "autor": {
            "type": "string",
            "example": "Carlos"
          },
          "positivo": {
            "type": "boolean",
            "example": 1
          },
          "comentario": {
            "type": "string",
            "example": "Me encanta la cancion"
          },
          "id_cancion_fk": {
            "type": "integer",
            "format": "int64",
            "example": 12
          }
        }
      },
      "listadoComentarios": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id_comentario": {
              "type": "integer",
              "format": "int64",
              "example": 1
            },
            "autor": {
              "type": "string",
              "example": "Carlos"
            },
            "positivo": {
              "type": "boolean",
              "example": 1
            },
            "comentario": {
              "type": "string",
              "example": "Me encanta la cancion"
            },
            "id_cancion_fk": {
              "type": "integer",
              "format": "int64",
              "example": 12
            }
          }
        },
        "example": [
          {
            "id_comentario": 1,
            "autor": "Carlos",
            "positivo": true,
            "comentario": "Me encanta la canción",
            "id_cancion_fk": 12
          },
          {
            "id_comentario": 2,
            "autor": "Ana",
            "positivo": false,
            "comentario": "No es de mi gusto",
            "id_cancion_fk": 10
          },
          {
            "id_comentario": 3,
            "autor": "Luis",
            "positivo": true,
            "comentario": "Excelente interpretación",
            "id_cancion_fk": 15
          }
        ]
      }
    },
    "examples": {
      "Created": {
        "summary": "Recurso creado",
        "value": {
          "mensaje": "Se creo el recurso con exito."
        }
      },
      "BadRequest": {
        "summary": "Solicitud Mala",
        "value": {
          "mensaje": "La solicitud fue mal generada."
        }
      },
      "InvalidParameters": {
        "summary": "Parámetros inválidos",
        "value": {
          "mensaje": "Los parámetros no corresponden."
        }
      },
      "NotFound": {
        "summary": "No encontrado",
        "value": {
          "mensaje": "No se encontraron resultados para el recurso solicitado."
        }
      },
      "Unauthorized": {
        "summary": "No autorizado",
        "value": {
          "mensaje": "No tienes permisos para esta operación."
        }
      }
    },
    "securitySchemes": {
      "api_key": {
        "type": "apiKey",
        "name": "token",
        "in": "header"
      }
    }
  }
}